version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/mv-os-backend
      - IMAGE_TAG=latest
      - echo Repository URI is $REPOSITORY_URI
      - echo Current directory
      - pwd
      - echo Listing files
      - ls -la
      - echo Finding Dockerfile
      - find . -name Dockerfile -type f 2>/dev/null | head -5
  build:
    commands:
      - echo Build started
      - echo Building Docker image
      - |
        DOCKERFILE_PATH=$(find . -name Dockerfile -type f -path "*/backend/Dockerfile" | head -1)
        if [ -z "$DOCKERFILE_PATH" ]; then
          echo ERROR: Dockerfile not found
          find . -name Dockerfile -type f
          exit 1
        fi
        BACKEND_DIR=$(dirname "$DOCKERFILE_PATH")
        echo Changing to directory: $BACKEND_DIR
        cd "$BACKEND_DIR"
        echo Building from: $(pwd)
        docker build -t $REPOSITORY_URI:latest -f Dockerfile .
        docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed
      - echo Pushing Docker images
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Image pushed successfully
